gbprod/yanky.nvim

README.md
doc/yanky.txt

You can pass several modes in list to `vim.keymap.set` function. Also, no need to pass empty `opts` table, since it is not `api` function.

docs: Improved default keymaps

---

lua/yanky.lua

fix(special-put): make ring works with special paste

---

lua/yanky/telescope/yank_history.lua

I am calling `require'yanky.config'.setup` twice to set mappings for telescope. This patch is needed to load the latest mappings for the picker.
The reason why this is needed is because I am using lazy-loading feature by packer.nvim for both yanky & telescope.
```lua
-- minimal setup for packer.nvim
{
"gbprod/yanky.nvim",
keys = {
{ "n", "<Plug>(YankyPutAfter)" },
},
setup = function()
vim.keymap.set('n', 'p', '<Plug>(YankyPutAfter)')
end,
config = function()
require("yanky").setup {}
end
},
{
"nvim-telescope/telescope.nvim",
cmd = { "Telescope" },
wants = { "yanky.nvim" },
config = function()
require("telescope").load_extension "yank_history"
local utils = require "yanky.utils"
local mapping = require "yanky.telescope.mapping"
local options = require("yanky.config").options …
```

Load telescope mappings on demand

---

lua/yanky.lua

Hi,
I noticed today that `YankyGPutBefore` and `YankyGPutAfter` are mixed up. Probably not so many people are actually using this feature :)
On a side note: the difference between `YankyPutBefore` and `YankyGPutBefore` (and likewise for `...After`) seems relevant only for linewise yanks, as is vanilla vim behaviour. What do you think about extending this to characterwise yanks? In other words, I would suggest adding a configuration option, so `YankyPutAfter` with a characterwise selection puts the cursor at the beginning of the pasted text. It should probably be an opt-in configuration option, because it overrides vanilla vim behaviour.

switch gputbefore and gputafter

---

lua/yanky/telescope/yank_history.lua

Partial revert of https://github.com/gbprod/yanky.nvim/commit/c4c794afd762a00ca543972e5b9e34ce9aa14a87
Overriding telescope mappings will only replace mappings in a mode.

fix!: replace telescope mappings instead of merging

---

lua/yanky/system_clipboard.lua

On wayland, when getting the contents of the system clipboard with `wl-paste`, `wl-paste` is launched.
`wl-paste` gets the window focus, so NEovim `FocusLost` is triggered.
This triggers an endless loop of focus lost/gained.
This PR fixes that.
Fixes https://github.com/gbprod/yanky.nvim/issues/37

fix: prevent focus gained/lost loop on wayland

---

README.md
lua/yanky/telescope/mapping.lua

Telescope default mapping use `<c-p>` to go to previous item, it's override by yanky's default mapping and I think it's not a good idea. I've changed this default mapping with `<c-g>` as it's not used by telescope.
Ref: #134

fix!: change yanky's telescope default mapping to avoid collision

---

lua/yanky/utils.lua

fix: use correct default register if no clipboard tool defined

---

README.md
lua/yanky.lua
lua/yanky/config.lua
lua/yanky/textobj.lua

Fixes #144
In addition, I'm adding a new setting for enabling the text object, to avoid unnecessarily tracking buffer changes when the feature is disabled. 
Since it is still experimental, I think it should be off by default.

fix(textobject): check for nil and add setting to enable

---

README.md
lua/yanky.lua
lua/yanky/config.lua

Followup of #145. The docs used `textobj` instead of the setting `textobject`, causing some confusion (see #146). This PR changes the setting to `textobj` everywhere for consistency with the name of the respective module.

fix(textobj): consistent naming

---

README.md
lua/yanky.lua
lua/yanky/config.lua

Using the `update_register_on_cycle` option, when you cycle through the ring, the contents of the register used to update will be updated with the last content cycled.
Ref: #76

feat(ring): allows to update register content on cycle

---

lua/yanky.lua

fix: avoid error when pasting twice with cancel_event is "move"

---

README.md

Hi, I have created a simple cmp-source for the yanky's history. Basically, this gives you suggestions from your clipboard history: https://github.com/chrisgrieser/cmp_yanky
I thought it might be worth mentioning in the README that such an integration exists :)

docs: mention `cmp_yanky`

---

lua/yanky/storage/sqlite.lua

This reverts commit 0dc8e0f262246ce4a891f0adf61336b3afe7c579.
As it seems to create bugs, I revert until I'll find how to fix it
Ref: #176 #177

Revert "feat: defer sqlite insert to avoid highligth blink (#99)"

---

README.md
lua/yanky/config.lua
lua/yanky/system_clipboard.lua
lua/yanky/utils.lua

if `opt.clipboard == ""` (because we want yanky to sync with system but
not in the primary position) then the `*` register is used, with no
way to choose `+`. So simply we add the necessary config option.

feat: config option for system clipboard register

---

lua/yanky/system_clipboard.lua
lua/yanky/utils.lua

The same logic that was initially only applied on focus gained, now also needs to be applied on focus lost.
https://github.com/LazyVim/LazyVim/issues/3321
Fixes #182

fix: prevent focus lost/gained loop on linux/wayland. Fixes #182

---

README.md

When user does not call `setup`, the option `on_substitute` should be wrapped as a function.

 docs: update `substitute.nvim` integration docs

---

lua/yanky/utils.lua

`provider#clipboard#Executable` can be very slow on remote machines (the following profile shows an execution time of 5 seconds).
I swapped the order in `utils.get_default_register`, eliminating unnecessary calls to `provider#clipboard#Executable` when the `clipboard` option is unset. This change significantly reduces both put latency and startup time.

perf: speed up default register determination

---

lua/yanky/sources/snacks.lua

This allows searching the yank history listing. Typing into the search box before would return the following error:
```
Unhandled async error:
...nvim/lazy/snacks.nvim/lua/snacks/picker/core/matcher.lua:484: attempt to index local 'str' (a nil value)
```

fix: make regcontents searchable in yanky picker

---

lua/yanky/highlight.lua

`vim.highlight` was renamed in https://github.com/neovim/neovim/pull/30840.
This PR uses the non-deprecated module if available.

feat: use `vim.hl` if available
