gbprod/yanky.nvim

README.md
lua/telescope/_extensions/yank_history.lua
lua/yanky.lua
lua/yanky/config.lua
lua/yanky/highlight.lua
lua/yanky/picker.lua
lua/yanky/telescope/mapping.lua
lua/yanky/telescope/yank_history.lua
lua/yanky/utils.lua

feat(picker): introduce yank history picker

---

README.md
lua/yanky.lua
lua/yanky/history.lua
lua/yanky/storage/memory.lua
lua/yanky/storage/shada.lua

feat(history): introduce YankyClearHistory command

---

README.md
lua/yanky/history.lua
lua/yanky/picker.lua
lua/yanky/storage/memory.lua
lua/yanky/storage/shada.lua
lua/yanky/telescope/mapping.lua

feat(picker): add action to remove entry

---

lua/yanky.lua

feat(yank): use option to set register for yank

---

README.md
lua/yanky/picker.lua
lua/yanky/telescope/mapping.lua

feat(telescope): introduce set register action

---

lua/yanky/picker.lua
lua/yanky/telescope/mapping.lua

fix(telescope): do not change cursor position on put

---

lua/yanky/picker.lua

fix(picker): replace new lines for builtin picker

---

lua/yanky/highlight.lua

fix(highlight): do not clear highlight when changing colorscheme

---

lua/yanky.lua
lua/yanky/history.lua

fix(ring): use correct value for first cycle

---

README.md

Your plugins is awesome to work with hydra! I made the integration if you like it!

docs: add hydra integration

---

README.md
lua/yanky.lua
lua/yanky/history.lua
lua/yanky/storage/sqlite.lua

feat(history): introduce sqlite storage

---

README.md
lua/yanky.lua
lua/yanky/wrappers.lua

feat(special-put): introduce Joined/Charwise/Blockwise

---

README.md
lua/yanky.lua
lua/yanky/wrappers.lua
spec/yanky/special_put_spec.lua

fix(put): correctly set cursor pos after gput filter

---

lua/yanky.lua

fix(put): incorrect put from expression register

---

lua/yanky/wrappers.lua
spec/init.lua
spec/yanky/system_clipboard_spec.lua

fix: do not call callback twice for joined put

---

LICENCE
lua/yanky.lua

fix: do not add to yank-ring if yanked to blackhole register

---

.gitignore
lua/yanky/picker.lua

fix: check if regcontents exists in YankyRingHistory

---

lua/yanky/highlight.lua

fix: use pcall with on_yank to avoid "end_col" error

---

lua/yanky/highlight.lua

fix: highlight on yank not working if highlight on put is disabled

---

lua/yanky.lua

fix(#120): always attach_cancel for cycle

---

README.md

I'm aware that @tpope is awesome and deserve the multiple credits.
But it looks like unintentional.

docs: Remove duplicate inspiration

---

README.md
lua/yanky/config.lua
lua/yanky/storage/sqlite.lua

feat: allows to change sqlite storage path

---

lua/yanky/picker.lua
lua/yanky/telescope/mapping.lua
lua/yanky/telescope/yank_history.lua

fix: replace visualy selected text when using telescope picker

---

README.md
lua/yanky/telescope/mapping.lua

feat: introduce put and set register telescope action

---

README.md
lua/yanky.lua
lua/yanky/integration.lua
lua/yanky/textobj.lua
lua/yanky/utils.lua

feat: introduce last_put text object

---

lua/yanky/telescope/mapping.lua
lua/yanky/textobj.lua

fix(telescope): schedule put to avoid marks disparition

---

README.md

docs: improve tpope/unimpaired keymaps visibility

---

.github/workflows/integration.yml
README.md
lua/yanky.lua

feat: make cycle keymap more mnemonical with next and previous

---

lua/yanky/telescope/mapping.lua

fix: better cursor position reset

---

lua/yanky/storage/sqlite.lua

feat: defer sqlite insert to avoid highligth blink

---

lua/yanky/system_clipboard.lua
lua/yanky/utils.lua

Another take at fixing focus-stealing clipboards.

fix: better way of dealing with focus-stealing clipboards

---

README.md
lua/yanky.lua
lua/yanky/wrappers.lua

feat: add permament_wrapper option to manage wsl

---

README.md
lua/yanky/textobj.lua

docs: fix last-put text-object docs
